# Coreveo SwiftLint Configuration

# Disabled rules that don't fit our project needs
disabled_rules:
  - trailing_whitespace

# Opt-in rules for better code quality
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_space_in_method_call
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Included paths (Swift source files only)
included:
  - Coreveo/Sources
  - CoreveoTests
  - CoreveoUITests

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - Carthage
  - .swiftpm
  - docs
  - scripts
  - .github

# Custom rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 400
  error: 1000

type_body_length:
  warning: 200
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - url
    - urlRequest
    - globalValueKey

type_name:
  min_length: 3
  max_length: 40

nesting:
  type_level:
    warning: 3
    error: 6

large_tuple:
  warning: 3
  error: 4

closure_body_length:
  warning: 20
  error: 50

enum_case_associated_values_count:
  warning: 5
  error: 6

# Reporter type
reporter: "xcode"

# Custom rules for Coreveo
custom_rules:
  # Prevent force unwrapping in production code
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: '!\s*$'
    message: "Force unwrapping is not allowed. Use optional binding or nil coalescing instead."
    severity: error
    
  # Require documentation for public APIs
  public_api_documentation:
    name: "Public API Documentation"
    regex: '^(public|open)\s+(class|struct|enum|protocol|func|var|let)'
    message: "Public APIs must be documented with /// comments."
    severity: warning
    
  # Prevent print statements in production
  no_print_statements:
    name: "No Print Statements"
    regex: 'print\s*\('
    message: "Use proper logging instead of print statements."
    severity: warning
